# Generated by Django 5.2.7 on 2026-03-07 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_companyprofile_emailnotification_jobalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('template_code', models.CharField(max_length=50, unique=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_size', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=20)),
                ('experience_level', models.CharField(max_length=50)),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('salary_median', models.IntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('sample_size', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['job_title', 'location'],
            },
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skill_category', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('total_questions', models.IntegerField(default=20)),
                ('passing_score', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_visibility',
            field=models.CharField(choices=[('open', 'Open to Opportunities'), ('closed', 'Not Looking for Jobs'), ('hidden', 'Hidden from Employers')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='remote_type',
            field=models.CharField(choices=[('no', 'No Remote'), ('partial', 'Partial Remote'), ('full', 'Fully Remote'), ('hybrid', 'Hybrid')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='culture',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('interview_type', models.CharField(choices=[('phone', 'Phone'), ('video', 'Video'), ('onsite', 'On-site')], default='video', max_length=20)),
                ('meeting_link', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.application')),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='recruitment.application')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('pro', 'Pro')], default='free', max_length=20)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('is_priority', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('resume_views', models.IntegerField(default=0)),
                ('applications_limit', models.IntegerField(default=10)),
                ('applications_used', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('employment_type', models.CharField(blank=True, max_length=20)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content_json', models.TextField(help_text='JSON storing resume sections')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='built_resumes', to='recruitment.candidate')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.resumetemplate')),
            ],
            options={
                'ordering': ['-is_primary', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('answers_json', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='recruitment.candidate')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='recruitment.skillassessment')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_companies', to='recruitment.candidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='recruitment.companyprofile')),
            ],
            options={
                'ordering': ['-followed_at'],
                'unique_together': {('candidate', 'company')},
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('title', models.CharField(max_length=200)),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_verified_employee', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='recruitment.companyprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='recruitment.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='recruitment.job')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
